vim.keymap.set('n', '<C-t>', ':Neotree toggle<CR>')
vim.keymap.set('n', '<C-h>', '<C-w>h')
vim.keymap.set('n', '<C-j>', '<C-w>j')
vim.keymap.set('n', '<C-k>', '<C-w>k')
vim.keymap.set('n', '<C-l>', '<C-w>l')
vim.keymap.set('n', ';', '/')
vim.keymap.set('n', '<C-c><C-c>', ':noh<CR>')
vim.keymap.set('n', '<', ':tabprevious<CR>')
vim.keymap.set('n', '>', ':tabnext<CR>')
